name: push-workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Versions
        run: |
          node -v
          npm -v

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Stash dist
        uses: actions/upload-artifact@master
        with:
          name: dist-${{ matrix.node-version }}-${{ github.run_id }}
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'

      - name: Unstash dist
        uses: actions/download-artifact@master
        with:
          name: dist-22.x-${{ github.run_id }}
          path: dist/

      - name: Install
        run: npm install
